[providers]
node = "18"

[phases.install]
cmds = ['npm ci --prefix server']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cd server && node server.js'

[variables]
NODE_ENV = 'production' 