[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd server && npm ci']

[phases.build]
cmds = ['cd server && npm run build 2>/dev/null || echo "No build script found"']

[start]
cmd = 'cd server && npm start' 