[providers]
node = "18"

[phases.install]
cmds = ['npm ci --prefix server']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'sh -c "cd server && node server.js"'

[variables]
NODE_ENV = 'production'
PORT = '3000' 