[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
  'npm ci',
  'cd server && npm ci'
]

[phases.build]
cmds = [
  'echo "Build phase - no build step needed for Node.js server"'
]

[start]
cmd = 'cd server && PORT=$PORT npm start'

[variables]
NODE_ENV = 'production' 