[build]
builder = "nixpacks"
buildCommand = "cd server && npm ci"
watchPatterns = ["server/**"]

[deploy]
startCommand = "node start.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 10
restartPolicyType = "on_failure"
numReplicas = 1

[env]
NODE_ENV = "production"
PORT = 3000 