[build]
builder = "nixpacks"
buildCommand = "cd server && npm ci"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 