[build]
builder = "nixpacks"
buildCommand = "npm ci --prefix server"
watchPatterns = ["server/**"]

[deploy]
startCommand = "cd server && node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

[env]
NODE_ENV = "production" 